# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/First_Task',
                'doc_host': 'https://Romasha-Guin-Brysk.github.io',
                'git_url': 'https://github.com/Romasha-Guin-Brysk/First_Task',
                'lib_path': 'First_Task'},
  'syms': {'First_Task.core': {'First_Task.core.foo': ('core.html#foo', 'First_Task/core.py')}}}
